### ISSUE TITLE
README states PHP 7.4+, but composer.json requires PHP 7.3+

### ISSUE THREAD

**Issue by jonnott** [laravel/serializable-closure#21]
..surely this wants to be in-tune with whatever the latest compatible laravel/framework requires, i.e. 7.3+ for L8.x?

**Comment by nunomaduro** [comment]
Composer requires PHP 7.3 to make this package installable on Laravel 8.x.

**Comment by jonnott** [comment]
> Composer requires PHP 7.3 to make this package installable on Laravel 8.x. Yet, the package does not support PHP 7.3.

This sounds like something could be broken for PHP 7.3 users then..?

**Comment by nunomaduro** [comment]
@jonnott We proxy for opis/closure when users are using PHP 7.3: https://github.com/laravel/framework/blob/8.x/src/Illuminate/Queue/SerializableClosureFactory.php.
