### ISSUE TITLE
Error: File name too long[36]

### ISSUE THREAD

**Issue by maher1337** [laravel/serializable-closure#35]
- Serializable Closure Version: 1.0.5
- Laravel Version: 8.81.0
- PHP Version: 8.1.1
- Database Driver & Version: MariaDB 10.6

### Description:

Using Octane to run some concurrent functions I get the following :
`[2022-02-01 14:31:06 ^76940.11]	WARNING	Server::task_unpack(): open(ravel\SerializableClosure\SerializableClosure":1:{s:12:"serializable";O:46:"Laravel\SerializableClosure\Serializers\Signed":2:{s:12:"serializable";s:721:"O:46:"Laravel\SerializableClosure\Serializers\Native":5:{s:3:"use";a:2:{s:11:"current_job";O:45:"Illum) failed, Error: File name too long[36]
`

### Steps To Reproduce:
```

Octane::concurrently([
                    fn () => (isset($track_input[0]) ? $this->jobtrack->insert($track_input) : null),
                    function () use ($image_input, $document_input) {
                        $this->job_images->insert($image_input);
                        $this->job_documents->insert($document_input);
                    }
                ]);
```

**Comment by maher1337** [comment]
I'd be more than happy to add more info just let me know what is needed.

**Comment by nunomaduro** [comment]
Can you try to create an open source repository, where I can see the issue happening locally?

**Comment by GrahamCampbell** [comment]
It's probably because you are trying to serialize the entire application. What's `$this->job_images`?

**Comment by maher1337** [comment]
@GrahamCampbell It's a Model constructed in the controller. Are we not allowed to use controller inherited models?

**Comment by maher1337** [comment]
Invoiking job_images statically works without a problem but using inheritance it fails.

**Comment by nunomaduro** [comment]
There is a limit on what you can import those "closures" when using `Octane::concurrently`. Please try to import the less as possible.
