### ISSUE TITLE
Class not found when type-hint is defined for closure created from method

### ISSUE THREAD

**Issue by rela589n** [laravel/serializable-closure#37]
- Serializable Closure Version: v1.1.0
- Laravel Version: not laravel scope
- PHP Version: 8.0.15

### Description:

I created closure from object method and tried to serialize it, however once unserialized it fails because of type hint used for this method.

### Steps To Reproduce:

Minimal code example is below:

Entry point script:

```php
<?php

use Laravel\SerializableClosure\SerializableClosure;
use Rela589n\PhpDecorationIssue\SerializableClosure\SerializableClosureIssue;

require 'vendor/autoload.php';

$object = new SerializableClosureIssue();

/** @var SerializableClosure $original */
$original = unserialize(
    serialize(
        new SerializableClosure(Closure::fromCallable([$object, 'reproduceIssue']))
    )
);

var_dump($original->getClosure()());
```

Class with method which will be used as closure:

```php
<?php

declare(strict_types=1);

namespace Rela589n\PhpDecorationIssue\SerializableClosure;

use JetBrains\PhpStorm\Immutable;

#[Immutable]
final class SerializableClosureIssue
{
    public function reproduceIssue(): Issue
    {
        return new Issue();
    }
}
```

Class for type-hinting in method:

```php
<?php

declare(strict_types=1);

namespace Rela589n\PhpDecorationIssue\SerializableClosure;

use JetBrains\PhpStorm\Immutable;

#[Immutable]
final class Issue
{

}
```

The foregoing code gives next issue:

```
PHP Fatal error:  Uncaught Error: Class "Issue" not found in laravel-serializable-closure://function (): \Issue
    {
        return new \Issue();
    }:4
Stack trace:
#0 /home/rela589n/projects/php-decoration-issue/serializable-closure.php(17): Rela589n\PhpDecorationIssue\SerializableClosure\SerializableClosureIssue::{closure}()
#1 {main}
  thrown in laravel-serializable-closure://function (): \Issue
    {
        return new \Issue();
    } on line 4
```

### Thanks

Thank you for this amazing package, it really complements missing PHP feature.

**Comment by rela589n** [comment]
I think this is related to how namespaces work in PHP. As classes `SerializableClosureIssue` and `Issue` reside in the same namespace, the latter is imported implicitly by PHP. Actually I tried to write `use Rela589n\PhpDecorationIssue\SerializableClosure\Issue;` in `SerializableClosureIssue.php` and it works fine this way. However it is not the real use case to import everything explicitly.

**Comment by nunomaduro** [comment]
@rela589n Are you able to pull request a failing test? We will work from there.

**Comment by rela589n** [comment]
@nunomaduro , yes I think so. I'm just wondering why did you close this issue?

**Comment by rela589n** [comment]
Added failing test in #38.
