### ISSUE TITLE
Memory leak in anonymous function

### ISSUE THREAD

**Issue by r4y7s** [laravel/serializable-closure#40]
- Serializable Closure Version: 1.1.1
- Laravel Version: -
- PHP Version: 7.4.3
- Database Driver & Version: -

### Description:
Memory leak in anonymous function when using SerializableClosure

### Steps To Reproduce:
```
use Laravel\SerializableClosure\SerializableClosure;

$baseMemory = memory_get_usage();

for ($i = 0; $i < PHP_INT_MAX; $i++) {
    $s = serialize(new SerializableClosure(fn() => 'james'));
    $u = unserialize($s);

    echo sprintf('%8d: ', $i), memory_get_usage() - $baseMemory, PHP_EOL;
    unset($s, $u);
}
```

It also occurs with the opis/closure package.
Link to a repository with the tests: https://github.com/r4y7s/laravel-serializable-closure-memory-leak

**Comment by nunomaduro** [comment]
This is a PHP engine scripting problem: https://bugs.php.net/bug.php?id=76982. That, at this time, affects all PHP versions supported by this package. Unfortunately, this issue can't be addressed in this repository.
