### ISSUE TITLE
PHP 7.3 is not supported.

### ISSUE THREAD

**Issue by isaacdarcilla** [laravel/serializable-closure#42]
- Serializable Closure Version: Latest
- Laravel Version: 8.75
- PHP Version: 7.3
- Database Driver & Version: MySQL

### Description:

I was trying to deploy my laravel app with jetstream installed, the only supported PHP version for the serve is 7.3. After deploying, this error shows.

```Laravel\SerializableClosure\Exceptions\PhpVersionNotSupportedException PHP 7.3 is not supported.```

```
Laravel\SerializableClosure\SerializableClosure::getClosure
vendor/laravel/serializable-closure/src/SerializableClosure.php:59
```

```php
    if (\PHP_VERSION_ID < 70400) {

            throw new PhpVersionNotSupportedException();

        }

 

        return call_user_func_array($this->serializable, func_get_args());

    }

 

    /**

     * Gets the closure.

     *

     * @return \Closure

     */

    public function getClosure()

    {

        if (\PHP_VERSION_ID < 70400) {

            throw new PhpVersionNotSupportedException();

        }
```
Is there any workaround?

**Comment by driesvints** [comment]
PHP 7.3 is indeed not supported. There's no workaround at this time.
