### ISSUE TITLE
serialization crashes on typed properties

### ISSUE THREAD

**Issue by henzeb** [laravel/serializable-closure#48]
- Serializable Closure Version: 1.2.0
- Laravel Version: 9.17.0
- PHP Version: 8.1.7
- Database Driver & Version:

### Description:
When a class is using a typed property that accepts closures, the code crashes, as you can't assign Native object where a Closure should be.

### Steps To Reproduce:

    class test {
    
        protected Closure $closure;
    
        public function __construct(Closure $closure)
        {
            $this->closure = $closure;
        }
    }
    
    $test = new test(function(){});
    
    serialize(new SerializableClosure(
        function() use ($test){
    
        }
    ));

**Comment by nunomaduro** [comment]
That's expected. The `SerializableClosure` serializes closures, not classes with closures properties.

**Comment by henzeb** [comment]
OK, but then add a caveat or erase the functionality from the code.

It works if not typed.
