### ISSUE TITLE
Unserialize from opis/closure serialization?

### ISSUE THREAD

**Issue by come-nc** [laravel/serializable-closure#49]
Hello,

We are migrating from opis/closure to this library, has anyone managed to unserialize data from opis/closure serialization into instances of `Laravel\SerializableClosure\SerializableClosure` ?
It would help with migration from one to the other. I would like to avoid to depend upon both library just for this. But I could not find much information about tricking php unserialize to use a class instead of another.

**Comment by nunomaduro** [comment]
We are not sure of your use case, yet you should deserialize the old data with `opis/closure`, and once all data is migrated, start using this package if you wish to migrate.

**Comment by come-nc** [comment]
Ok, I did a few tests and came to the same conclusion.

A bit sad because it means I’ll need to depend on both lib for a few releases but it seems PHP serialization system is not something easy to play with.

Thank you for your answer.
