### ISSUE TITLE
Check for readonly properties

### ISSUE THREAD

**Issue by RV7PR** [laravel/serializable-closure#89]
In this old issue https://github.com/opis/closure/issues/28 I had a problem with readonly properties so they fixed it with this https://github.com/opis/closure/compare/3.1.5...3.1.6 though this (```$property->getDeclaringClass()->isUserDefined()```) isn't needed for PHP >= 8.1, you can just skip the readonly properties like https://github.com/laravel/serializable-closure/pull/87

**Comment by driesvints** [comment]
Thanks @RV7PR. @rust17 could this be an alternative implementation?

**Comment by rust17** [comment]
I believe these are two separate issues. 

The `$property->getDeclaringClass()->isUserDefined()` method solves the `Cannot write property` problem, whereas `$property->isReadOnly()` deals with the `Cannot modify readonly property` issue. As you can see, the `opis/closure` encounters the `Cannot modify readonly property` [issue](https://github.com/opis/closure/issues/129) during unserialization, similar to what was reported in https://github.com/laravel/framework/issues/51877.

Therefore, I don't think this is an alternative solution. 

Additionally, this line of code(`$property->getDeclaringClass()->isUserDefined()`) is already present in `laravel/serializable-closure`: https://github.com/laravel/serializable-closure/blob/master/src/Serializers/Native.php#L371.

**Comment by driesvints** [comment]
Thanks @rust17
